#-----------------------------------------------------------------------------
#' ggsave2
#' @description Save a ggplot2 plot to multiple filetypes
#' @importFrom ggplot2 ggsave
#' @importFrom glue glue
#' @importFrom stringr str_remove str_c
#' @importFrom ggplot2 last_plot
#' @export
#-----------------------------------------------------------------------------

ggsave2 = function(filename, plot = last_plot(), filetypes = c("pdf", "png"), ...) {
  for (filetype in filetypes) {
    ggsave(glue("{str_remove(filename, str_c(filetypes[1], "$")}{filetype}"), plot = plot, ...)
  }
}

# -----------------------------------------------------------------------------
#' geom_pvalue
#' @description Add p-value to ggplot2 
#' @param rstatix_result A tibble generated by rstatix::*_test()
#' @param hide_ns Hide non-significant p-values
#' @param p_label The label of p-value
#' @param ref.group The reference group
#' @param nsd_away The distance of non-significant p-values
#' @importFrom dplyr mutate
#' @importFrom rstatix add_y_position add_significance
#' @importFrom ggpubr stat_pvalue_manual
#' @export

geom_pvalue = function(
  rstatix_result,
  hide_ns = T,
  p_label = 'p.signif',
  ref.group = NULL,
  nsd_away = 0.5,
  ...
) {
  require(rstatix)
  require(ggpubr)
  data = rstatix_result |>
    add_significance("p")
  mean = add_y_position(data, scales = "free", step.increase = 0, fun = "mean")$y.position[1]
  mean_sd = add_y_position(data, scales = "free", step.increase = 0, fun = "mean_sd")$y.position[1]
  sd = mean_sd - mean
  data = data |>
    add_y_position(scales = "free", step.increase = 0, ref.group = ref.group) |>
    mutate(y.position = y.position + sd * nsd_away)
  stat_pvalue_manual(
    data,
    label = p_label,
    inherit.aes = F,
    hide.ns = hide_ns,
    label.size = 8,
    bracket.size = 0.6,
    tip.length = 0.02,
    step.increase = 0.05,
    vjust = 0.6,
    ...
  )
}

# if (F) {
#   require(rstatix)
#   require(ggpubr)

#   t_res = ToothGrowth %>%
#     t_test(len ~ dose)
#   ggplot(ToothGrowth, aes(as.character(dose), len)) +
#     geom_point() +
#     geom_boxplot() +
#     geom_pvalue(t_res)
# }

# -----------------------------------------------------------------------------
#' geom_point
#' @description Add p-value to ggplot2
#' @param rstatix_result A tibble generated by rstatix::*_test()
#' @param hide_ns Hide non-significant p-values
#' @param p_label The label of p-value
#' @param ref.group The reference group
#' @param nsd_away The distance of non-significant p-values
#' @importFrom dplyr mutate
#' @importFrom rstatix add_y_position add_significance
#' @importFrom ggpubr stat_pvalue_manual
#' @export


geom_point_border = function(..., size = 3.0, stroke_size = 0.7) {
  bgsize = size + stroke_size * 2
  list(
    geom_point(size = bgsize, color = "black", pch = 19),
    geom_point(color = "white", size = size, pch = 19),
    geom_point(..., pch = 19, size = size)
  )
}
